### ISSUE TITLE
Incorrect 3D

### ISSUE THREAD

**Issue by ioncorimenia** [Spaqin/fbwo-3ds#1]
The 3D is completely inverted. This makes it unplayable and nauseating in 3D.

**Comment by Spaqin** [comment]
It's not inverted - if I remember correctly, going the other way was not helpful as well. I don't recommend playing in 3D at all, as the game is entirely 2D anyway. I implemented it only because... it was rather simple :c to do.

**Comment by ioncorimenia** [comment]
Oh, ok. What part of the sf2d_draw_texture function regulates the 3D elevation? Do you manually draw sprites twice for each eye?

**Comment by Spaqin** [comment]
Frame needs to be rendered from scratch for each screen (or eye). 3D works by having an offset in X position - just like in real life, if you close one eye, then switch the open eye, there is a slight shift for objects close to you and the background is basically not changed.

**Comment by ioncorimenia** [comment]
I was hoping that there was an Y value that I'm just not seeing, but ok. It's probably not worth it to try and fix the 3D anyway. I feel like I'm the only one that uses the 3DS's 3D.
